### ISSUE TITLE
Fresh install on Pi. Cannot start. 

### ISSUE THREAD

**Issue by thomahawk72** [TuomoKu/SPX-GC#85]
Just cloned git repo onto a RPi 4 on Ubuntu 
Ran "npm install".
On staring with "node ./server.js" the following error appears:

/usr/local/scripts/SPX/SPX-GC/server.js:972
  if ( config.general?.disableSeveralControllersWarning==true ) {
                      ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

**Comment by TuomoKu** [comment]
Node update will 99% fix this.
